### ISSUE TITLE
Can't connect pixeldroid after 0.11.2 update

### ISSUE THREAD

**Issue by ashemsay** [YunoHost-Apps/pixelfed_ynh#167]
### Describe the bug

Since I updated to 0.11.2 I can not login anymore with Pixeldroid on my Android phone.

### Context

- Hardware: *Dedicated server*
- YunoHost version:
  ```
  yunohost: 
    repo: stable
    version: 4.3.6.2
  yunohost-admin: 
    repo: testing
    version: 4.3.4.1
  moulinette: 
    repo: stable
    version: 4.3.3.1
  ssowat: 
    repo: stable
    version: 4.3.3.1
  ```
- I have access to my server: *Through SSH + through the webadmin + direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: my instance was migrated from another server using the official migration procedure
- Using, or trying to install package version/branch: 0.11.2~ynh1
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- Enter the instance address in Pixeldroid, authorize Pixeldroid in the following screen, I get sent back to the instance selection screen.

### Expected behavior

The app gets authenticated and I can browse my instance.

### Logs

Relevant nginx logs: https://bin.idrix.fr/?f28712637a9d5865#DCLVCEpCM8QVRmyKFWVNLxjpkAq6VavnaR49mAAuKG5P
No message from the Pixeldroid app.
