### ISSUE TITLE
Erreur 404

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/pixelfed_ynh#2]
```
yunohost: 
  repo: stable
  version: 3.0.0.1
yunohost-admin: 
  repo: stable
  version: 3.0.0
moulinette: 
  repo: stable
  version: 3.0.0
ssowat: 
  repo: stable
  version: 3.0.0
```
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
```
Bonjour,

je installé pixelfed_ynh sur une Yunohost fraîchement migré en Stretch, tout c'est bien passé mais quand je clique sur Login ou Register je tombe sur une erreur 404.

Avez-vous besoin d'autre info ?
