### ISSUE TITLE
i can't set up "Sign-in with Mastodon"

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/pixelfed_ynh#281]
### Describe the bug

i can't make this workking:
https://github.com/pixelfed/pixelfed/pull/4545

### Context

-     Hardware: VPS
-     YunoHost version:
```
root@krashboyz:/var/www/pixelfed# yunohost --version
yunohost: 
  repo: stable
  version: 12.0.9.2
yunohost-admin: 
  repo: stable
  version: 12.0.4
yunohost-portal: 
  repo: stable
  version: 12.0.7
moulinette: 
  repo: stable
  version: 12.0.3
ssowat: 
  repo: stable
  version: 12.0.3
```
-     I have access to my server: Through SSH && through the webadmin
-     Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
-     Using package version: 0.12.4~ynh1

### Steps to reproduce

added at the end of /var/www/pixelfed/.env
```
## Sign In with Mastodon 
## cf https://github.com/pixelfed/pixelfed/pull/4545
PF_LOGIN_WITH_MASTODON_ENABLED=true
PF_LOGIN_WITH_MASTODON_DOMAINS="masto.krashboyz.org"
PF_LOGIN_WITH_MASTODON_SKIP_EMAIL=false
```
then reload the conf and  restarted the service
```
root@krashboyz:/var/www/pixelfed# sudo -u pixelfed php8.3 artisan config:cache && sudo -u pixelfed php8.3 artisan cache:clear

   INFO  Configuration cached successfully.  


   INFO  Application cache cleared successfully.
```
(i tried without the sudo -u pixelfed too without any more success)

```
yunohost service restart pixelfed
```

but i never have the option as i could see it on the pixelfed.fr server.

I don't know where I'm supposed to keep digging for far, I just found another weird thing as described on 
https://github.com/YunoHost-Apps/pixelfed_ynh/issues/280  
and I have no idea if it's correlated
